# Generated by Django 3.1.1 on 2020-10-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201001_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='postt',
            name='sample',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
