# Generated by Django 3.1.1 on 2020-09-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_by', models.CharField(max_length=100)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
