# Generated by Django 3.1.1 on 2020-10-01 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_postt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rollno',
            new_name='rn',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
