# Generated by Django 3.1.1 on 2020-10-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Password',
            field=models.CharField(max_length=50),
        ),
    ]
