# Generated by Django 3.1.1 on 2020-11-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Email',
            field=models.CharField(max_length=30),
        ),
    ]
