# Generated by Django 3.1.2 on 2020-10-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cummunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cummunity_name', models.CharField(max_length=20)),
                ('user', models.ManyToManyField(to='relapp.User')),
            ],
        ),
    ]
