# Generated by Django 3.1.2 on 2020-10-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0003_auto_20201001_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
