# Generated by Django 3.1.2 on 2020-10-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
