# Generated by Django 3.1.2 on 2020-10-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relapp', '0002_cummunity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cummunity',
            name='user',
            field=models.ManyToManyField(related_name='cummunity', to='relapp.User'),
        ),
    ]
