# Generated by Django 3.1.1 on 2020-09-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='salary',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
